#ifndef CXXMIDI_VERSION_HPP
#define CXXMIDI_VERSION_HPP

#define CXXMIDI_VERSION_STRINGIFY2(s) #s
#define CXXMIDI_VERSION_STRINGIFY(s) CXXMIDI_VERSION_STRINGIFY2(s)

#define CXXMIDI_VERSION_MAJOR 0
#define CXXMIDI_VERSION_MINOR 2
#define CXXMIDI_VERSION CXXMIDI_VERSION_STRINGIFY(CXXMIDI_VERSION_MAJOR) "." CXXMIDI_VERSION_STRINGIFY(CXXMIDI_VERSION_MINOR)

#endif // CXXMIDI_VERSION_HPP

