name: cmakelint
on: push
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cmakelint
    - run: cmakelint `find . -name CMakeLists.txt`